### PR TITLE
use key parameter

### PR DESCRIPTION
**Pull request by arons**
In my current redmine installation (2.5.2) looks like that http basic authentication is not working for api key.
Redmine doc reports that there are three possibilities to pass the api key, I've just added one by passing the key as a parameter in the url (X-Redmine-API-Key don't know if still supported).

Thanks for the nice work of the plugin.

### CODE REVIEW

**Comment by kdzwinel** [comment]
Hey! Thanks for contribution. I'm holding it for now - basic auth is much cleaner (IMO) than `"?key="`. I'll wait and see if others have the same issue. Meanwhile, can you report that on redmine.com? Maybe that's just a bug in 2.5.2?

**Comment by arons** [comment]
I've reported by redmine (http://www.redmine.org/issues/18113) anyway I think would be nice to let the user choose the auth method he prefer (may you want to change the default value of settings).
Thanks.

**Comment by arons** [comment]
Hi,
the redmine ticket is closed, there was a missing config for fastcgi, now basic authentication is working properly.
Feel free to discharge the request.

Thanks

**Comment by kdzwinel** [comment]
It's great to hear, thank you @arons !

**Pull request closed without merging**
