### PR TITLE
request Url option, update delay option

### PR DESCRIPTION
**Pull request by Regul777**
add update request Url for custom update request
add custom update delay option

### CODE REVIEW

**Comment by kdzwinel** [comment]
Thanks, that was fast! I'll review your code, test it and merge it after work.

**Comment by Regul777** [comment]
Hey! Everyone wait for this update :-)

**Comment by kdzwinel** [comment]
Hi, your code looks good but I haven't got time to test it yesterday. Sorry, I'll do it today. On the occasion I want to also change the look of the options page basing on the https://github.com/frankkohlhepp/fancy-settings project.

**Comment by Regul777** [comment]
fancy-settings looks pretty cool :-) Ok. We will wait as much as need :-) Thx you for your job!

**Comment by kdzwinel** [comment]
I've included your code in version 0.6 I'm already working on: https://github.com/kdzwinel/Redmine-Issues-Checker/tree/version-06 , you can monitor my progress :)

**Comment by Regul777** [comment]
It's cool! :-) Wait for update.

**Pull request merged**
